import React, { useState } from 'react';
import { State, City, Country } from 'country-state-city'; // Import State, City, and Country from country-state-city
import './PatientMasterForm.css';
import { sendDataToPatientBackend } from 'C:\\Users\\jaint\\OneDrive\\Desktop\\Finkepp\\Form\\form\\src\\api.js'; // Correct import path


const PatientMasterForm = () => {
    // State to manage form fields
    const [formData, setFormData] = useState({
        uhid: '',
        name: '',
        aadhar: '',
        dob: '',
        email: '',
        age: '',
        gender: '',
        phone: '',
        addr: '',
        country: '',
        area: '',
        state: '',
        postalcode: '',
        city: '',
        altmobno: '',
        relationship: '',
        bloodGroup: '',
        remarks: '',
        patienthist: ''
    });

    const familyMembers = [
        'Self',
        'Spouse',
        'Child',
        'Parent',
        'Sibling',
        'Grandparent',
        'Grandchild',
        'Aunt',
        'Uncle',
        'Niece',
        'Nephew',
        'Cousin',
        'In-Law',
        'Other'
    ];
    // Fetch countries
    const countries = Country.getAllCountries();

    // Fetch states based on selected country
    const fetchStates = (selectedCountry) => {
        const statesOfSelectedCountry = State.getStatesOfCountry(selectedCountry);
        return statesOfSelectedCountry;
    };

    // Fetch cities based on selected state
    const fetchCities = (selectedState) => {
        const citiesOfSelectedState = City.getCitiesOfState(formData.country, selectedState);
        return citiesOfSelectedState;
    };


    // Handle form field changes
    // Handle form field changes
    const handleInputChange = (e) => {
        const { name, value } = e.target;

        // If state is changed, reset city field and fetch cities of selected state
        if (name === 'country') {
            setFormData(prevState => ({
                ...prevState,
                state: '', // Reset state field
                city: '', // Reset city field
                [name]: value,
            }));
        } else {
            setFormData(prevState => ({
                ...prevState,
                [name]: value,
            }));
        }
    };


    // Handle form submission
    const handleSubmit = (e) => {
        e.preventDefault();
        const dataToSend = { data: formData };

        // Call sendDataToPatientBackend function with formData
        sendDataToPatientBackend(dataToSend)
            .then(() => {
                console.log('Data successfully inserted');
            })
            .catch(error => {
                console.error('Error inserting data:', error);
            });

        // Move the logging after the API call
        console.log(JSON.stringify(dataToSend));
    };


    return (
        <div>
            <h1 style={{ textAlign: "center", fontWeight: "bold" }}>Patient Master Form</h1>
            <div className="form-container">
                <div className="left-section">
                    <div className="form-group">
                        <label htmlFor="uhid">UHID:</label>
                        <input
                            type="text"
                            name="uhid"
                            value={formData.uhid}
                            onChange={handleInputChange}
                            placeholder="Autogenerated UHID"
                            className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="name">Name:</label>
                        <input
                            type="text"
                            name="name"
                            value={formData.firstName} // Should be formData.name
                            onChange={handleInputChange}
                            placeholder="Enter your name"
                            className="form-control"
                        />

                    </div>
                    <div className="form-group">
                        <label htmlFor="dob">Date Of Birth:</label>
                        <input
                            type="date"
                            name="dob"
                            value={formData.dob}
                            onChange={handleInputChange}
                            placeholder="Enter your D.O.B."
                            className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="age">Age/Gender:</label>
                        <input
                            type="number"
                            name="age"
                            value={formData.age}
                            onChange={handleInputChange}
                            placeholder="Enter your Age"
                            className="form-control"
                        />
                        <input
                            type="radio"
                            name="gender"
                            value="male"
                            checked={formData.gender === "male"}
                            onChange={handleInputChange}
                        />
                        Male
                        <input
                            type="radio"
                            name="gender"
                            value="female"
                            checked={formData.gender === "female"}
                            onChange={handleInputChange}
                        />
                        Female
                    </div>
                </div>
                <div className="right-section" style={{ marginTop: '44px' }}>
                    <div className="form-group">
                        <label htmlFor="aadhar">Aadhar No.:</label>
                        <input
                            type="text"
                            name="aadhar"
                            value={formData.aadhar}
                            onChange={handleInputChange}
                            placeholder="Enter your Aadhar"
                            className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="email">Email:</label>
                        <input
                            type="email"
                            name="email"
                            value={formData.email}
                            onChange={handleInputChange}
                            placeholder="Enter your email address"
                            className="form-control"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="phone">Phone:</label>
                        <input
                            type="tel"
                            name="phone"
                            value={formData.phone}
                            onChange={handleInputChange}
                            placeholder="Enter your phone number"
                            className="form-control"
                        />
                    </div>
                </div>
            </div>

            <div className="form-container">
                <div className="left-section">
                    <div className="form-group">
                        <label htmlFor="addr">Address:</label>
                        <input
                            type="text"
                            name="addr"
                            value={formData.addr}
                            onChange={handleInputChange}
                            placeholder="Enter you address line 1"
                            className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="area">Area:</label>
                        <input
                            type="text"
                            name="area"
                            value={formData.area}
                            onChange={handleInputChange}
                            placeholder="Enter your Area"
                            className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label htmlFor="postalcode">Postal Code: </label>
                        <input
                            type="text"
                            name="postalcode"
                            value={formData.postalcode}
                            onChange={handleInputChange}
                            placeholder="Enter your Pincode"
                            className="form-control"
                        />
                    </div>
                </div>
                <div className="right-section">
                    <div className="form-group">
                        <label htmlFor="country">Country:</label>
                        <select
                            name="country"
                            value={formData.country}
                            onChange={handleInputChange}
                            className="form-control"
                        >
                            <option value="">Select Country</option>
                            {countries.map(country => (
                                <option key={country.isoCode} value={country.isoCode}>{country.name}</option>
                            ))}
                        </select>
                    </div>
                    <div className="form-group">
                        <label htmlFor="state">State:</label>
                        <select
                            name="state"
                            value={formData.state}
                            onChange={handleInputChange}
                            className="form-control"
                        >
                            <option value="">Select State</option>
                            {fetchStates(formData.country).map(state => (
                                <option key={state.isoCode} value={state.isoCode}>{state.name}</option>
                            ))}
                        </select>
                    </div>
                    <div className="form-group">
                        <label htmlFor="city">City:</label>
                        <select
                            name="city"
                            value={formData.city}
                            onChange={handleInputChange}
                            className="form-control"
                        >
                            <option value="">Select City</option>
                            {formData.state && fetchCities(formData.state).map(city => (
                                <option key={city.name} value={city.name}>{city.name}</option>
                            ))}
                        </select>
                    </div>
                </div>
            </div>
            <div className="form-container">
                <div className="left-section">
                    <div className="form-group">
                        <label htmlFor="altmobno">Alternate Mob. No.: </label>
                        <input
                            type="text"
                            name="altmobno"
                            value={formData.altmobno}
                            onChange={handleInputChange}
                            placeholder="Enter your ALT MOB. NO."
                            className="form-control"
                        />
                    </div>
                </div>
                <div className="right-section">
                    <div className="form-group">
                        <label htmlFor="relationship">Relationship:</label>
                        {formData.relationship === 'Other' ? (
                            <input
                                type="text"
                                name="otherRelationship"
                                value={formData.otherRelationship}
                                onChange={handleInputChange}
                                placeholder="Enter Other Relationship"
                                className="form-control"
                            />
                        ) : (
                            <select
                                name="relationship"
                                value={formData.relationship}
                                onChange={handleInputChange}
                                className="form-control"
                            >
                                <option value="">Select Relationship</option>
                                {familyMembers.map(member => (
                                    <option key={member} value={member}>{member}</option>
                                ))}
                            </select>
                        )}
                    </div>
                </div>
            </div>
            <div className="form-last-container">
                <div className="section">
                    <div className="left-section">
                        <div className="form-group">
                            <label htmlFor="bloodGroup">Blood Group:</label>
                            <select
                                name="bloodGroup"
                                value={formData.bloodGroup}
                                onChange={handleInputChange}
                                className="form-control"
                            >
                                <option value="">Select Blood Group</option>
                                <option value="A+">A+</option>
                                <option value="A-">A-</option>
                                <option value="B+">B+</option>
                                <option value="B-">B-</option>
                                <option value="AB+">AB+</option>
                                <option value="AB-">AB-</option>
                                <option value="O+">O+</option>
                                <option value="O-">O-</option>
                            </select>
                        </div>
                    </div>
                    <div className="right-section">
                        <div className="form-group">
                            <label htmlFor="remarks">Remarks: </label>
                            <input
                                type="text"
                                name="remarks"
                                value={formData.remarks}
                                onChange={handleInputChange}
                                placeholder="Enter Remarks"
                                className="form-control"
                            />
                        </div>
                    </div>
                </div>
                <div className='medication'>
                    <div className="form-group">
                        <label htmlFor="patienthist">Patient History:</label>
                        <textarea
                            name="patienthist"
                            value={formData.patienthist}
                            onChange={handleInputChange}
                            className="form-control"
                            rows={4} // Specify the number of rows for the textarea
                        />
                    </div>
                </div>
            </div>
            <div className="submit-container">
                <button type="submit" className="btn-submit" onClick={handleSubmit}>
                    Submit
                </button>
            </div>
        </div>
    );
};

export default PatientMasterForm;
